# Generated by Django 5.1.4 on 2026-08-18 13:37

import careers.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the page title in search results. Leave blank to use the title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Shown under the title in search results. Aim for 140-160 characters.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630. Falls back to the hero image if blank.', upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='Only set this if the content is republished from elsewhere.')),
                ('noindex', models.BooleanField(default=False, help_text='Hide this page from search engines.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Set a future date to schedule. Required to go live.', null=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('work_mode', models.CharField(choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20)),
                ('experience_min_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience_max_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('responsibilities', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('requirements', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('nice_to_have', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('benefits', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('is_open', models.BooleanField(default=True)),
                ('apply_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('resume', models.FileField(help_text='PDF, DOC, or DOCX. 5 MB max.', upload_to='careers/resumes/%Y/%m/', validators=[careers.models.validate_resume_extension, careers.models.validate_resume_size])),
                ('portfolio_url', models.URLField(blank=True)),
                ('cover_note', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('new', 'New'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
