# Generated by Django 5.1.4 on 2026-08-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_path', models.CharField(db_index=True, help_text='Path only, with leading slash. e.g. /respond-to-rfps-faster/', max_length=400, unique=True)),
                ('new_path', models.CharField(max_length=400)),
                ('permanent', models.BooleanField(default=True, help_text='301 if set, 302 if not.')),
                ('hit_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['old_path'],
            },
        ),
    ]
