# Generated by Django 5.1.4 on 2026-08-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('blurb', models.CharField(blank=True, max_length=200)),
                ('icon', models.ImageField(blank=True, upload_to='taxonomy/industries/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('show_in_nav', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'industries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('blurb', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
