# Generated by Django 5.1.4 on 2026-08-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='blurb',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
