# Generated by Django 5.1.4 on 2026-08-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the page title in search results. Leave blank to use the title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Shown under the title in search results. Aim for 140-160 characters.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630. Falls back to the hero image if blank.', upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='Only set this if the content is republished from elsewhere.')),
                ('noindex', models.BooleanField(default=False, help_text='Hide this page from search engines.')),
                ('hero_heading', models.CharField(max_length=200)),
                ('hero_subheading', models.TextField(blank=True)),
                ('hero_cta_label', models.CharField(default='Talk to an expert', max_length=40)),
                ('hero_cta_url', models.CharField(blank=True, max_length=300)),
                ('hero_image', models.ImageField(blank=True, upload_to='home/')),
                ('expertise_heading', models.CharField(default='Our area of expertise', max_length=160)),
                ('expertise_intro', models.TextField(blank=True)),
                ('use_cases_heading', models.CharField(default='AI use cases for every industry', max_length=160)),
                ('case_studies_heading', models.CharField(default='Driving transformation across industries', max_length=160)),
                ('insights_heading', models.CharField(default='Insights that drive measurable impact', max_length=160)),
                ('show_partners', models.BooleanField(default=True)),
                ('show_client_logos', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('capabilities_deck', models.FileField(blank=True, help_text='The downloadable capabilities PDF.', upload_to='decks/')),
            ],
            options={
                'verbose_name': 'home page',
            },
        ),
    ]
