# Generated by Django 5.1.4 on 2026-08-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading',
            field=models.TextField(help_text="Up to three lines. The middle line renders in the muted two-tone colour — this is the site's signature headline treatment."),
        ),
    ]
