# Generated by Django 5.1.4 on 2026-08-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_office_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='calendly_url',
            field=models.URLField(blank=True, help_text="Your Calendly scheduling link, e.g. https://calendly.com/you/30min. Every 'Book a call' button and the demo page's scheduling embed is hidden entirely when this is blank — nothing breaks, they just don't render."),
        ),
    ]
