# Generated by Django 5.1.4 on 2026-08-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_add_calendly_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='stat_4_label',
            field=models.CharField(blank=True, help_text='e.g. Years in operation.', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_4_value',
            field=models.CharField(blank=True, help_text='e.g. 6+. Leave blank to omit this slot.', max_length=24),
        ),
    ]
