# Generated by Django 5.1.4 on 2026-08-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_add_stat_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the page title in search results. Leave blank to use the title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Shown under the title in search results. Aim for 140-160 characters.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630. Falls back to the hero image if blank.', upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='Only set this if the content is republished from elsewhere.')),
                ('noindex', models.BooleanField(default=False, help_text='Hide this page from search engines.')),
                ('heading', models.CharField(max_length=200)),
                ('intro_paragraph_1', models.TextField(blank=True)),
                ('intro_paragraph_2', models.TextField(blank=True)),
                ('capabilities_eyebrow', models.CharField(default="What we're good at", max_length=80)),
                ('capabilities_heading', models.CharField(default='Depth in a few places', max_length=160)),
                ('expectations_eyebrow', models.CharField(default='How we work', max_length=80)),
                ('expectations_heading', models.CharField(default='What you should expect', max_length=160)),
                ('cta_heading', models.CharField(default="Tell us what's stuck", max_length=160)),
                ('cta_body', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'about page',
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='pages.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='pages.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
