# Generated by Django 5.1.4 on 2026-08-18 13:37

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('solutions', '0002_service_parent_service_show_in_form_dropdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField(blank=True)),
                ('column_1_label', models.CharField(max_length=60)),
                ('column_2_label', models.CharField(max_length=60)),
                ('column_3_label', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('under_10k', 'Under $10K'), ('10_25k', '$10K – $25K'), ('25_50k', '$25K – $50K'), ('50_100k', '$50K – $100K'), ('over_100k', '$100K+'), ('unsure', 'Not sure yet')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='project_stage',
            field=models.CharField(blank=True, choices=[('idea', 'Just an idea'), ('prototype', 'Early prototype / MVP'), ('active', 'Active development'), ('live', 'Live product needing improvement'), ('scaling', 'Scaling / expansion')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='service_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='solutions.service'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='utm_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='source_platform',
            field=models.CharField(choices=[('direct', 'Direct'), ('upwork', 'Upwork'), ('clutch', 'Clutch'), ('google', 'Google'), ('linkedin', 'LinkedIn')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_thumbnail',
            field=models.ImageField(blank=True, upload_to='testimonials/video/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='source',
            field=models.CharField(choices=[('contact', 'Contact page'), ('demo', 'Book a demo'), ('handbook', 'Handbook download'), ('footer', 'Footer CTA'), ('popup', 'Lead popup'), ('hire', 'Hire developers'), ('other', 'Other')], db_index=True, default='contact', max_length=20),
        ),
        migrations.CreateModel(
            name='ComparisonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=140)),
                ('icon', models.ImageField(blank=True, upload_to='comparison/')),
                ('column_1_value', models.CharField(blank=True, max_length=120)),
                ('column_2_value', models.CharField(blank=True, max_length=120)),
                ('column_3_value', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='marketing.comparisontable')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field()),
                ('placement', models.CharField(choices=[('home', 'Home'), ('services', 'Services'), ('hire', 'Hire'), ('contact', 'Contact'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='solutions.service')),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['placement', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LeadPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('heading', models.CharField(max_length=120)),
                ('subheading', models.CharField(blank=True, max_length=120)),
                ('footer_text', models.TextField(blank=True)),
                ('panel_image', models.ImageField(blank=True, upload_to='popup/')),
                ('form_heading', models.CharField(max_length=120)),
                ('submit_label', models.CharField(max_length=40)),
                ('success_message', models.TextField()),
                ('trigger', models.CharField(choices=[('delay', 'After a delay'), ('scroll', 'After scrolling'), ('exit', 'On exit intent'), ('delay_or_exit', 'Delay or exit intent')], default='delay_or_exit', max_length=20)),
                ('delay_seconds', models.PositiveSmallIntegerField(default=25)),
                ('scroll_percent', models.PositiveSmallIntegerField(default=50)),
                ('frequency_days', models.PositiveSmallIntegerField(default=7, help_text="Don't show again for this many days after a dismissal.")),
                ('hide_after_submit_days', models.PositiveSmallIntegerField(default=90)),
                ('show_on_mobile', models.BooleanField(default=False)),
                ('exclude_paths', models.TextField(blank=True, help_text='One path per line, e.g. /careers/.')),
                ('badges', models.ManyToManyField(blank=True, to='marketing.recognition')),
            ],
            options={
                'verbose_name': 'lead popup',
            },
        ),
        migrations.CreateModel(
            name='PopupStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='marketing.leadpopup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
