# Generated by Django 5.1.4 on 2026-08-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_comparisontable_contactsubmission_budget_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='source',
            field=models.CharField(choices=[('contact', 'Contact page'), ('demo', 'Book a demo'), ('handbook', 'Handbook download'), ('footer', 'Footer CTA'), ('popup', 'Lead popup'), ('hire', 'Hire developers'), ('chat', 'Chat widget'), ('other', 'Other')], db_index=True, default='contact', max_length=20),
        ),
    ]
