# Generated by Django 5.1.4 on 2026-08-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('visitor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('escalated_to_contact', models.BooleanField(default=False)),
                ('source_url', models.CharField(blank=True, help_text='Page the widget was opened from.', max_length=400)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Visitor'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('cited_sources', models.JSONField(blank=True, default=list, help_text='[{title, url}, ...] the assistant grounded this reply in.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
