# Generated by Django 5.1.4 on 2026-08-18 12:34

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(choices=[('enterprise', 'Enterprise'), ('smb', 'SMB'), ('startup', 'Startup')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('icon', models.ImageField(blank=True, upload_to='solutions/org/')),
                ('target_url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['org_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the page title in search results. Leave blank to use the title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Shown under the title in search results. Aim for 140-160 characters.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630. Falls back to the hero image if blank.', upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='Only set this if the content is republished from elsewhere.')),
                ('noindex', models.BooleanField(default=False, help_text='Hide this page from search engines.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Set a future date to schedule. Required to go live.', null=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('card_image', models.ImageField(blank=True, upload_to='products/cards/')),
                ('hero_image', models.ImageField(blank=True, upload_to='products/heroes/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('industries', models.ManyToManyField(blank=True, related_name='products', to='taxonomy.industry')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the page title in search results. Leave blank to use the title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Shown under the title in search results. Aim for 140-160 characters.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630. Falls back to the hero image if blank.', upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='Only set this if the content is republished from elsewhere.')),
                ('noindex', models.BooleanField(default=False, help_text='Hide this page from search engines.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Set a future date to schedule. Required to go live.', null=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='One line, shown in the nav dropdown.', max_length=160)),
                ('summary', models.TextField(blank=True, help_text='Card and listing text.')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to='services/icons/')),
                ('hero_image', models.ImageField(blank=True, upload_to='services/heroes/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='taxonomy.servicecluster')),
            ],
            options={
                'ordering': ['cluster__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the page title in search results. Leave blank to use the title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Shown under the title in search results. Aim for 140-160 characters.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630. Falls back to the hero image if blank.', upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='Only set this if the content is republished from elsewhere.')),
                ('noindex', models.BooleanField(default=False, help_text='Hide this page from search engines.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Set a future date to schedule. Required to go live.', null=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(help_text='Shown on the homepage industry tabs.')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='use-cases/')),
                ('cta_label', models.CharField(default='Explore now', max_length=40)),
                ('cta_url', models.CharField(blank=True, help_text="Leave blank to link to this use case's own page.", max_length=300)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='use_cases', to='taxonomy.industry')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_cases', to='solutions.service')),
            ],
            options={
                'ordering': ['industry__order', 'order', 'title'],
            },
        ),
    ]
