# Generated by Django 5.1.4 on 2026-08-18 13:37

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a top-level group within the cluster.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='solutions.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_form_dropdown',
            field=models.BooleanField(default=False, help_text="Include in the contact form's service picker."),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the page title in search results. Leave blank to use the title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Shown under the title in search results. Aim for 140-160 characters.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630. Falls back to the hero image if blank.', upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='Only set this if the content is republished from elsewhere.')),
                ('noindex', models.BooleanField(default=False, help_text='Hide this page from search engines.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Set a future date to schedule. Required to go live.', null=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('logo', models.ImageField(blank=True, upload_to='tech/')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('show_in_stack_grid', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technologies', to='solutions.service')),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'ordering': ['service', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HireRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the page title in search results. Leave blank to use the title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Shown under the title in search results. Aim for 140-160 characters.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630. Falls back to the hero image if blank.', upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='Only set this if the content is republished from elsewhere.')),
                ('noindex', models.BooleanField(default=False, help_text='Hide this page from search engines.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Set a future date to schedule. Required to go live.', null=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('starting_rate', models.CharField(blank=True, max_length=60)),
                ('hero_image', models.ImageField(blank=True, upload_to='hire/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('related_services', models.ManyToManyField(blank=True, related_name='hire_roles', to='solutions.service')),
                ('skills', models.ManyToManyField(blank=True, related_name='hire_roles', to='solutions.technology')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
